// Auto-generated by scan_repos_status.ps1
window.LAST_SCAN = '06/09/2026 15:27:56';
window.MACHINE_NAME = 'LINH';
window.PROJECTS_DATA = [
    {
        "Name":  "AI-Space",
        "Branch":  "N/A",
        "Uncommitted":  0,
        "UncommittedFiles":  [

                             ],
        "UncommittedStat":  "",
        "LastCommitHash":  "",
        "LastCommitMsg":  "N/A",
        "LastCommitDate":  "N/A",
        "LastCommitStat":  "",
        "LastCommitFiles":  [

                            ],
        "RecentCommits":  [

                          ],
        "RemoteSync":  "No Git",
        "Health":  "[-] Trong",
        "Priority":  "Dọn dẹp",
        "Category":  "stubs",
        "Desc":  "Thu muc trong phuc vu thu nghiem tu do.",
        "Progress":  0,
        "Tech":  "Thu muc trong",
        "Blocker":  "Trong.",
        "Action":  "Xoa hoac don dep de workspace gon gang.",
        "QuickCmd":  ""
    },
    {
        "Name":  "AI-STock",
        "Branch":  "master",
        "Uncommitted":  0,
        "UncommittedFiles":  [

                             ],
        "UncommittedStat":  {

                            },
        "LastCommitHash":  "0699e23",
        "LastCommitMsg":  "docs(plan): prune BCTC and corporate action phases per requirement, refocus roadmap on run center, outbox bot, and portfolio dossier",
        "LastCommitDate":  "2026-09-06 (4 hours ago)",
        "LastCommitStat":  "2 files changed, 31 insertions(+), 91 deletions(-)",
        "LastCommitFiles":  [
                                "M\tCONTEXT.md",
                                "M\tPLAN.md"
                            ],
        "RecentCommits":  [
                              {
                                  "Hash":  "0699e23",
                                  "Time":  "4 hours ago",
                                  "Msg":  "docs(plan): prune BCTC and corporate action phases per requirement, refocus roadmap on run center, outbox bot, and portfolio dossier"
                              },
                              {
                                  "Hash":  "cdd8175",
                                  "Time":  "4 hours ago",
                                  "Msg":  "docs(plan): add master implementation plan across all phases and align context for next session"
                              },
                              {
                                  "Hash":  "b7c9bf6",
                                  "Time":  "4 hours ago",
                                  "Msg":  "docs(context): document durable architectural invariants, weekend freshness fix, and execution roadmap for next session"
                              }
                          ],
        "RemoteSync":  "Up-to-date",
        "Health":  "[OK] Clean",
        "Priority":  "P1",
        "Category":  "active p0p1",
        "Desc":  "Nen tang phan tich dinh luong chung khoan VN (CANSLIM, Minervini) \u0026 bot Telegram 24/7.",
        "Progress":  85,
        "Tech":  [
                     "Python",
                     "Streamlit",
                     "vnstock v4",
                     "SQLite",
                     "GitHub Actions"
                 ],
        "Blocker":  "Can giam sat do on dinh cron GitHub Actions 15:05 hang ngay.",
        "Action":  "Giam sat runner atomic va mo rong bo loc nhom nganh co phieu.",
        "QuickCmd":  "streamlit run app.py"
    },
    {
        "Name":  "GPMB-SmartAuto",
        "Branch":  "main",
        "Uncommitted":  0,
        "UncommittedFiles":  [

                             ],
        "UncommittedStat":  {

                            },
        "LastCommitHash":  "34f2157",
        "LastCommitMsg":  "Initial commit",
        "LastCommitDate":  "2026-07-30 (5 weeks ago)",
        "LastCommitStat":  "2 files changed, 4 insertions(+)",
        "LastCommitFiles":  [

                            ],
        "RecentCommits":  [
                              {
                                  "Hash":  "34f2157",
                                  "Time":  "5 weeks ago",
                                  "Msg":  "Initial commit"
                              }
                          ],
        "RemoteSync":  "Unknown (fetch failed)",
        "Health":  "[!] Remote unavailable",
        "Priority":  "P3",
        "Category":  "stubs",
        "Desc":  "Ke hoach tu dong hoa ho so boi thuong, ho tro tai dinh cu \u0026 giai phong mat bang.",
        "Progress":  5,
        "Tech":  [
                     "Blueprint",
                     "Chua co code"
                 ],
        "Blocker":  "Chua co dac ta nghiep vu va kien truc.",
        "Action":  "Soan thao tai lieu dac ta luong kiem dem va phuong an boi thuong.",
        "QuickCmd":  ""
    },
    {
        "Name":  "law-wiki-bidding-v2",
        "Branch":  "main",
        "Uncommitted":  0,
        "UncommittedFiles":  [

                             ],
        "UncommittedStat":  {

                            },
        "LastCommitHash":  "a47b1fc",
        "LastCommitMsg":  "docs: update LOG.md with TT-80 ingest completion",
        "LastCommitDate":  "2026-05-14 (4 months ago)",
        "LastCommitStat":  "1 file changed, 40 insertions(+)",
        "LastCommitFiles":  [
                                "M\twiki/LOG.md"
                            ],
        "RecentCommits":  [
                              {
                                  "Hash":  "a47b1fc",
                                  "Time":  "4 months ago",
                                  "Msg":  "docs: update LOG.md with TT-80 ingest completion"
                              },
                              {
                                  "Hash":  "f66c699",
                                  "Time":  "4 months ago",
                                  "Msg":  "docs: update README with v1.4.0 TT-80 completion"
                              },
                              {
                                  "Hash":  "ea266c3",
                                  "Time":  "4 months ago",
                                  "Msg":  "feat: ingest TT-80/2025 (single document, 6 articles)"
                              }
                          ],
        "RemoteSync":  "Up-to-date",
        "Health":  "[OK] Clean",
        "Priority":  "P2",
        "Category":  "active",
        "Desc":  "Co so tri thuc Luat Dau thau 2023, ND 214/2025, TT 79, TT 80/2025 (LLM Wiki Graph).",
        "Progress":  75,
        "Tech":  [
                     "Markdown",
                     "Obsidian",
                     "Python Ingest",
                     "Knowledge Graph"
                 ],
        "Blocker":  "Chua co giao dien tra cuu truc tiep; chua tong hop so sanh quy trinh.",
        "Action":  "Soan thao bai tong hop so sanh quy trinh va tich hop chatbot RAG.",
        "QuickCmd":  "obsidian://open?vault=law-wiki-bidding-v2"
    },
    {
        "Name":  "Mini-app-QLDA",
        "Branch":  "main",
        "Uncommitted":  4,
        "UncommittedFiles":  [
                                 "M README.md",
                                 "M docs/data-hub-mini-cutover-plan.md",
                                 "[sensitive path redacted]",
                                 "?? docs/mini-data-hub-zalo-runbook.md"
                             ],
        "UncommittedStat":  "2 files changed, 15 insertions(+)",
        "LastCommitHash":  "3b01b9c",
        "LastCommitMsg":  "feat(mini,api): implement 8-checkpoint hardening, baseline matrix and clean release pipeline",
        "LastCommitDate":  "2026-09-06 (64 minutes ago)",
        "LastCommitStat":  "20 files changed, 544 insertions(+), 62 deletions(-)",
        "LastCommitFiles":  [
                                "M\t.gitignore",
                                "M\tapps/api/app/api/v2/mini.py",
                                "M\tapps/api/app/config.py",
                                "M\tapps/api/app/infrastructure/mini_data_hub_client.py",
                                "M\tapps/api/app/main.py",
                                "[sensitive path redacted]"
                            ],
        "RecentCommits":  [
                              {
                                  "Hash":  "3b01b9c",
                                  "Time":  "64 minutes ago",
                                  "Msg":  "feat(mini,api): implement 8-checkpoint hardening, baseline matrix and clean release pipeline"
                              },
                              {
                                  "Hash":  "e76ced0",
                                  "Time":  "2 weeks ago",
                                  "Msg":  "up vốn"
                              },
                              {
                                  "Hash":  "e148359",
                                  "Time":  "2 weeks ago",
                                  "Msg":  "up vướng mắc"
                              }
                          ],
        "RemoteSync":  "Up-to-date",
        "Health":  "[!] Uncommitted (4)",
        "Priority":  "P0",
        "Category":  "active p0p1 git",
        "Desc":  "Quan ly du an dau tu cong, giai ngan von \u0026 vuong mac qua Zalo Mini App va Web.",
        "Progress":  70,
        "Tech":  [
                     "FastAPI",
                     "TypeScript",
                     "ZaUI",
                     "PostgreSQL",
                     "Docker"
                 ],
        "Blocker":  "Dang dung temporary tunnel; cho Zalo App ID de submit review Mini App.",
        "Action":  "Commit tai lieu cutover-plan \u0026 runbook do dang; chuan bi gateway.",
        "QuickCmd":  "poetry run uvicorn app.main:app --reload"
    },
    {
        "Name":  "personal-agentkit",
        "Branch":  "master",
        "Uncommitted":  0,
        "UncommittedFiles":  [

                             ],
        "UncommittedStat":  {

                            },
        "LastCommitHash":  "6cd7a5d",
        "LastCommitMsg":  "feat(sync): support linking 106 AgentKit base skills as independent junctions",
        "LastCommitDate":  "2026-09-02 (4 days ago)",
        "LastCommitStat":  "1 file changed, 13 insertions(+), 4 deletions(-)",
        "LastCommitFiles":  [
                                "M\tsync.ps1"
                            ],
        "RecentCommits":  [
                              {
                                  "Hash":  "6cd7a5d",
                                  "Time":  "4 days ago",
                                  "Msg":  "feat(sync): support linking 106 AgentKit base skills as independent junctions"
                              },
                              {
                                  "Hash":  "b1d12bf",
                                  "Time":  "4 days ago",
                                  "Msg":  "feat(skill-creator): add skill-creator following Progressive Disclosure 3-Tier architecture"
                              },
                              {
                                  "Hash":  "e16d6cb",
                                  "Time":  "4 days ago",
                                  "Msg":  "feat: initialize Personal AgentKit v1.0 with skills, agents, rules, and sync engine"
                              }
                          ],
        "RemoteSync":  "Local only",
        "Health":  "[OK] Local Clean",
        "Priority":  "P2",
        "Category":  "active",
        "Desc":  "He thong quan ly \u0026 dong bo Skills, Agents, Hooks, Rules cho Antigravity, Cursor, Codex.",
        "Progress":  85,
        "Tech":  [
                     "PowerShell",
                     "Markdown",
                     "JSON Schema",
                     "106 Skills"
                 ],
        "Blocker":  "Chua co remote repository tren GitHub (moi commit cuc bo).",
        "Action":  "Tao private GitHub repo de push ma nguon va viet them skill xay dung.",
        "QuickCmd":  ".\\sync.ps1"
    },
    {
        "Name":  "Phan mem kiem tra ho so XD",
        "Branch":  "N/A",
        "Uncommitted":  0,
        "UncommittedFiles":  [

                             ],
        "UncommittedStat":  "",
        "LastCommitHash":  "",
        "LastCommitMsg":  "N/A",
        "LastCommitDate":  "N/A",
        "LastCommitStat":  "",
        "LastCommitFiles":  [

                            ],
        "RecentCommits":  [

                          ],
        "RemoteSync":  "No Git",
        "Health":  "[-] Trong",
        "Priority":  "Ý tưởng",
        "Category":  "stubs",
        "Desc":  "Y tuong phan mem kiem tra loi ho so thiet ke ban ve thi cong va du toan XD.",
        "Progress":  0,
        "Tech":  "Thu muc trong",
        "Blocker":  "Chua khoi tao code base.",
        "Action":  "Len danh muc cac quy chuan va loi ho so pho bien can kiem tra.",
        "QuickCmd":  ""
    },
    {
        "Name":  "Skills",
        "Branch":  "N/A",
        "Uncommitted":  0,
        "UncommittedFiles":  [

                             ],
        "UncommittedStat":  "",
        "LastCommitHash":  "",
        "LastCommitMsg":  "N/A",
        "LastCommitDate":  "N/A",
        "LastCommitStat":  "",
        "LastCommitFiles":  [

                            ],
        "RecentCommits":  [

                          ],
        "RemoteSync":  "No Git",
        "Health":  "[*] Tai lieu tho (144 files)",
        "Priority":  "P3",
        "Category":  "stubs",
        "Desc":  "Kho tai lieu tho chua 144 files mo ta 106 engineering skills (BATCH 1-5).",
        "Progress":  50,
        "Tech":  [
                     "Raw JSON",
                     "Batch Dumps"
                 ],
        "Blocker":  "Du lieu tho chua chuan hoa theo cau truc SKILL.md.",
        "Action":  "Trich xuat cac ky nang huu ich sang personal-agentkit/skills.",
        "QuickCmd":  ""
    },
    {
        "Name":  "Smart",
        "Branch":  "main",
        "Uncommitted":  0,
        "UncommittedFiles":  [

                             ],
        "UncommittedStat":  {

                            },
        "LastCommitHash":  "8ec5d5e",
        "LastCommitMsg":  "Initial commit",
        "LastCommitDate":  "2026-07-30 (5 weeks ago)",
        "LastCommitStat":  "1 file changed, 2 insertions(+)",
        "LastCommitFiles":  [

                            ],
        "RecentCommits":  [
                              {
                                  "Hash":  "8ec5d5e",
                                  "Time":  "5 weeks ago",
                                  "Msg":  "Initial commit"
                              }
                          ],
        "RemoteSync":  "Unknown (fetch failed)",
        "Health":  "[!] Remote unavailable",
        "Priority":  "Dọn dẹp",
        "Category":  "stubs",
        "Desc":  "Phien ban cu hoac repository rong cua SmartDoc.",
        "Progress":  5,
        "Tech":  "Gitattributes",
        "Blocker":  "Du an khong con su dung.",
        "Action":  "Xoa hoac di chuyen vao thu muc _archive.",
        "QuickCmd":  ""
    },
    {
        "Name":  "SmartDoc-UIpath",
        "Branch":  "main",
        "Uncommitted":  0,
        "UncommittedFiles":  [

                             ],
        "UncommittedStat":  {

                            },
        "LastCommitHash":  "3e58df3",
        "LastCommitMsg":  "feat(templatize): add reverse template generator for Word Add-in and Web Admin (76/76 tests green)",
        "LastCommitDate":  "2026-09-05 (28 hours ago)",
        "LastCommitStat":  "12 files changed, 3039 insertions(+), 333 deletions(-)",
        "LastCommitFiles":  [
                                "M\t.gitignore",
                                "M\tapp/main.py",
                                "A\tapp/routers/templatize.py",
                                "A\tapp/services/templatize_service.py",
                                "M\tdocs/ai_handoff.md",
                                "M\tfrontend/admin.html"
                            ],
        "RecentCommits":  [
                              {
                                  "Hash":  "3e58df3",
                                  "Time":  "28 hours ago",
                                  "Msg":  "feat(templatize): add reverse template generator for Word Add-in and Web Admin (76/76 tests green)"
                              },
                              {
                                  "Hash":  "54454ca",
                                  "Time":  "2 days ago",
                                  "Msg":  "update addin"
                              },
                              {
                                  "Hash":  "1f98597",
                                  "Time":  "3 weeks ago",
                                  "Msg":  "update import file"
                              }
                          ],
        "RemoteSync":  "Up-to-date",
        "Health":  "[OK] Clean",
        "Priority":  "P0",
        "Category":  "active p0p1 git",
        "Desc":  "Sinh van ban hanh chinh \u0026 quyet dinh tu dong thay the UiPath, Word Task Pane 2016.",
        "Progress":  80,
        "Tech":  [
                     "FastAPI",
                     "python-docx",
                     "SQLite",
                     "Office.js"
                 ],
        "Blocker":  "Can xac thuc nguoi dung va manifest ben vung truoc khi chay LAN.",
        "Action":  "Git pull commit moi tu origin/main; nap mau TB phan cong nhiem vu vao DB.",
        "QuickCmd":  "poetry run uvicorn app.main:app --port 8000 --reload"
    },
    {
        "Name":  "Zalo-work-hub",
        "Branch":  "main",
        "Uncommitted":  0,
        "UncommittedFiles":  [

                             ],
        "UncommittedStat":  {

                            },
        "LastCommitHash":  "a5a07e5",
        "LastCommitMsg":  "feat: harden atomic lease claims, report idempotency, and full zalo_user_id support",
        "LastCommitDate":  "2026-09-05 (23 hours ago)",
        "LastCommitStat":  "19 files changed, 323 insertions(+), 155 deletions(-)",
        "LastCommitFiles":  [
                                "M\tPROJECT_MEMORY.md",
                                "M\tapp/api/server.py",
                                "M\tapp/api/v1/reports.py",
                                "M\tapp/api/v1/routes.py",
                                "M\tapp/api/v1/webhooks.py",
                                "M\tapp/dashboard/client.py"
                            ],
        "RecentCommits":  [
                              {
                                  "Hash":  "a5a07e5",
                                  "Time":  "23 hours ago",
                                  "Msg":  "feat: harden atomic lease claims, report idempotency, and full zalo_user_id support"
                              },
                              {
                                  "Hash":  "ff46fc4",
                                  "Time":  "23 hours ago",
                                  "Msg":  "test: add automated acceptance protocol verification script (K1-K11)"
                              },
                              {
                                  "Hash":  "a8f0f7f",
                                  "Time":  "23 hours ago",
                                  "Msg":  "fix: route repo model fallback, backup executable, and config env load order"
                              }
                          ],
        "RemoteSync":  "Behind (1)",
        "Health":  "[!] Behind Remote",
        "Priority":  "P1",
        "Category":  "active p0p1 git",
        "Desc":  "Bot dieu hanh cong viec, boc tach tin nhan tieng Viet \u0026 nhac hen 4 moc qua Zalo.",
        "Progress":  65,
        "Tech":  [
                     "FastAPI",
                     "SQLite WAL",
                     "Streamlit",
                     "OpenZCA",
                     "Ubuntu"
                 ],
        "Blocker":  "Can may chu Ubuntu co OpenZCA CLI va cau hinh danh muc assignee_routes.",
        "Action":  "Deploy 3 systemd services len Ubuntu server va cau hinh mapping Zalo.",
        "QuickCmd":  "poetry run streamlit run app/dashboard/dashboard_app.py"
    }
];
