// Auto-generated by scan_repos_status.ps1
window.LAST_SCAN = '04/09/2026 11:02:30';
window.PROJECTS_DATA = [
    {
        "Name":  "AI-Space",
        "Branch":  "N/A",
        "Uncommitted":  0,
        "RemoteSync":  "No Git",
        "Health":  "[-] Trong",
        "LastCommit":  "N/A",
        "Priority":  "Dọn dẹp",
        "Category":  "stubs",
        "Desc":  "Thu muc trong phuc vu thu nghiem tu do.",
        "Progress":  0,
        "Tech":  "Thu muc trong",
        "Blocker":  "Trong.",
        "Action":  "Xoa hoac don dep de workspace gon gang.",
        "QuickCmd":  ""
    },
    {
        "Name":  "AI-STock",
        "Branch":  "master",
        "Uncommitted":  0,
        "RemoteSync":  "Up-to-date",
        "Health":  "[OK] Clean",
        "LastCommit":  "2026-08-31 (4 days ago) | fix(pipeline): resolve P0/P1 audit items (suppress live auto-seed, atomic cloud pipeline, standardized DATA_MODE, IngestResult, and pipeline test suite)",
        "Priority":  "P1",
        "Category":  "active p0p1",
        "Desc":  "Nen tang phan tich dinh luong chung khoan VN (CANSLIM, Minervini) \u0026 bot Telegram 24/7.",
        "Progress":  85,
        "Tech":  [
                     "Python",
                     "Streamlit",
                     "vnstock v4",
                     "SQLite",
                     "GitHub Actions"
                 ],
        "Blocker":  "Can giam sat do on dinh cron GitHub Actions 15:05 hang ngay.",
        "Action":  "Giam sat runner atomic va mo rong bo loc nhom nganh co phieu.",
        "QuickCmd":  "streamlit run app.py"
    },
    {
        "Name":  "GPMB-SmartAuto",
        "Branch":  "main",
        "Uncommitted":  0,
        "RemoteSync":  "Up-to-date",
        "Health":  "[OK] Clean",
        "LastCommit":  "2026-07-30 (5 weeks ago) | Initial commit",
        "Priority":  "P3",
        "Category":  "stubs",
        "Desc":  "Ke hoach tu dong hoa ho so boi thuong, ho tro tai dinh cu \u0026 giai phong mat bang.",
        "Progress":  5,
        "Tech":  [
                     "Blueprint",
                     "Chua co code"
                 ],
        "Blocker":  "Chua co dac ta nghiep vu va kien truc.",
        "Action":  "Soan thao tai lieu dac ta luong kiem dem va phuong an boi thuong.",
        "QuickCmd":  ""
    },
    {
        "Name":  "law-wiki-bidding-v2",
        "Branch":  "main",
        "Uncommitted":  0,
        "RemoteSync":  "Up-to-date",
        "Health":  "[OK] Clean",
        "LastCommit":  "2026-05-14 (4 months ago) | docs: update LOG.md with TT-80 ingest completion",
        "Priority":  "P2",
        "Category":  "active",
        "Desc":  "Co so tri thuc Luat Dau thau 2023, ND 214/2025, TT 79, TT 80/2025 (LLM Wiki Graph).",
        "Progress":  75,
        "Tech":  [
                     "Markdown",
                     "Obsidian",
                     "Python Ingest",
                     "Knowledge Graph"
                 ],
        "Blocker":  "Chua co giao dien tra cuu truc tiep; chua tong hop so sanh quy trinh.",
        "Action":  "Soan thao bai tong hop so sanh quy trinh va tich hop chatbot RAG.",
        "QuickCmd":  "obsidian://open?vault=law-wiki-bidding-v2"
    },
    {
        "Name":  "Mini-app-QLDA",
        "Branch":  "main",
        "Uncommitted":  3,
        "RemoteSync":  "Up-to-date",
        "Health":  "[!] Uncommitted (3)",
        "LastCommit":  "2026-08-22 (13 days ago) | up vốn",
        "Priority":  "P0",
        "Category":  "active p0p1 git",
        "Desc":  "Quan ly du an dau tu cong, giai ngan von \u0026 vuong mac qua Zalo Mini App va Web.",
        "Progress":  70,
        "Tech":  [
                     "FastAPI",
                     "TypeScript",
                     "ZaUI",
                     "PostgreSQL",
                     "Docker"
                 ],
        "Blocker":  "Dang dung temporary tunnel; cho Zalo App ID de submit review Mini App.",
        "Action":  "Commit tai lieu cutover-plan \u0026 runbook do dang; chuan bi gateway.",
        "QuickCmd":  "poetry run uvicorn app.main:app --reload"
    },
    {
        "Name":  "personal-agentkit",
        "Branch":  "master",
        "Uncommitted":  0,
        "RemoteSync":  "Local only",
        "Health":  "[OK] Local Clean",
        "LastCommit":  "2026-09-02 (2 days ago) | feat(sync): support linking 106 AgentKit base skills as independent junctions",
        "Priority":  "P2",
        "Category":  "active",
        "Desc":  "He thong quan ly \u0026 dong bo Skills, Agents, Hooks, Rules cho Antigravity, Cursor, Codex.",
        "Progress":  85,
        "Tech":  [
                     "PowerShell",
                     "Markdown",
                     "JSON Schema",
                     "106 Skills"
                 ],
        "Blocker":  "Chua co remote repository tren GitHub (moi commit cuc bo).",
        "Action":  "Tao private GitHub repo de push ma nguon va viet them skill xay dung.",
        "QuickCmd":  ".\\sync.ps1"
    },
    {
        "Name":  "Phan mem kiem tra ho so XD",
        "Branch":  "N/A",
        "Uncommitted":  0,
        "RemoteSync":  "No Git",
        "Health":  "[-] Trong",
        "LastCommit":  "N/A",
        "Priority":  "Ý tưởng",
        "Category":  "stubs",
        "Desc":  "Y tuong phan mem kiem tra loi ho so thiet ke ban ve thi cong va du toan XD.",
        "Progress":  0,
        "Tech":  "Thu muc trong",
        "Blocker":  "Chua khoi tao code base.",
        "Action":  "Len danh muc cac quy chuan va loi ho so pho bien can kiem tra.",
        "QuickCmd":  ""
    },
    {
        "Name":  "Skills",
        "Branch":  "N/A",
        "Uncommitted":  0,
        "RemoteSync":  "No Git",
        "Health":  "[*] Tai lieu tho (144 files)",
        "LastCommit":  "N/A",
        "Priority":  "P3",
        "Category":  "stubs",
        "Desc":  "Kho tai lieu tho chua 144 files mo ta 106 engineering skills (BATCH 1-5).",
        "Progress":  50,
        "Tech":  [
                     "Raw JSON",
                     "Batch Dumps"
                 ],
        "Blocker":  "Du lieu tho chua chuan hoa theo cau truc SKILL.md.",
        "Action":  "Trich xuat cac ky nang huu ich sang personal-agentkit/skills.",
        "QuickCmd":  ""
    },
    {
        "Name":  "Smart",
        "Branch":  "main",
        "Uncommitted":  0,
        "RemoteSync":  "Up-to-date",
        "Health":  "[OK] Clean",
        "LastCommit":  "2026-07-30 (5 weeks ago) | Initial commit",
        "Priority":  "Dọn dẹp",
        "Category":  "stubs",
        "Desc":  "Phien ban cu hoac repository rong cua SmartDoc.",
        "Progress":  5,
        "Tech":  "Gitattributes",
        "Blocker":  "Du an khong con su dung.",
        "Action":  "Xoa hoac di chuyen vao thu muc _archive.",
        "QuickCmd":  ""
    },
    {
        "Name":  "SmartDoc-UIpath",
        "Branch":  "main",
        "Uncommitted":  6,
        "RemoteSync":  "Up-to-date",
        "Health":  "[!] Uncommitted (6)",
        "LastCommit":  "2026-08-13 (3 weeks ago) | update import file",
        "Priority":  "P0",
        "Category":  "active p0p1 git",
        "Desc":  "Sinh van ban hanh chinh \u0026 quyet dinh tu dong thay the UiPath, Word Task Pane 2016.",
        "Progress":  80,
        "Tech":  [
                     "FastAPI",
                     "python-docx",
                     "SQLite",
                     "Office.js"
                 ],
        "Blocker":  "Can xac thuc nguoi dung va manifest ben vung truoc khi chay LAN.",
        "Action":  "Git pull commit moi tu origin/main; nap mau TB phan cong nhiem vu vao DB.",
        "QuickCmd":  "poetry run uvicorn app.main:app --port 8000 --reload"
    },
    {
        "Name":  "Zalo-work-hub",
        "Branch":  "main",
        "Uncommitted":  0,
        "RemoteSync":  "Up-to-date",
        "Health":  "[OK] Clean",
        "LastCommit":  "2026-09-04 (2 hours ago) | feat: add subtask append command, past occurrence protection, and Zalo group dashboard column",
        "Priority":  "P1",
        "Category":  "active p0p1",
        "Desc":  "Bot dieu hanh cong viec, boc tach tin nhan tieng Viet \u0026 nhac hen 4 moc qua Zalo.",
        "Progress":  65,
        "Tech":  [
                     "FastAPI",
                     "SQLite WAL",
                     "Streamlit",
                     "OpenZCA",
                     "Ubuntu"
                 ],
        "Blocker":  "Can may chu Ubuntu co OpenZCA CLI va cau hinh danh muc assignee_routes.",
        "Action":  "Deploy 3 systemd services len Ubuntu server va cau hinh mapping Zalo.",
        "QuickCmd":  "poetry run streamlit run app/dashboard/dashboard_app.py"
    }
];
